version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  lint:
    executor:
      name: android/android # Docker Executor https://circleci.com/developer/ja/orbs/orb/circleci/android#executors-android
      sdk-version: "30"
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Run ktlint
          command: ./gradlew lint
      - android/save-gradle-cache

workflows:
  main:
    jobs:
      - lint
