version: 2.1

orbs:
  android: circleci/android@1.0.3
  ruby: circleci/ruby@1.2.0

jobs:
  lint:
    docker:
      - image: cimg/android:2021.10.2
    resource_class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew lint
      - android/save-gradle-cache

  beta:
    docker:
      - image: cimg/android:2021.10.2
    resource_class: 2xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - ruby/install-deps
      - run: bundle exec fastlane beta
      - android/save-gradle-cache
      - android/save-build-cache

workflows:
  main:
    jobs:
      - lint
      - beta:
          context:
            - mobile
